server:
  port: 8085
  servlet:
    context-path: /rider

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate.ddl-auto: "update"
    show-sql: true
  sql:
    init:
      mode: always