spring:
  datasource:
    druid:
      test-while-idle: true
      validation-query: SELECT 1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: "jdbc:mysql://192.168.190.128:3306/rider_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true"
    username: "dev"
    password: "developer"
  redis:
    host: 192.168.190.128
    port: 6379
    timeout: 3000 #最大等待时间，3000ms,超时抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1
