server:
  port: 8085
  servlet:
    context-path: /rider

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    #服务器位于弗吉尼亚州，如果感觉连接很慢，打开VPN
    url: "jdbc:mysql://ec2-3-88-85-162.compute-1.amazonaws.com:3306/rider_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true"
    username: "dev"
    password: "developer"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate.ddl-auto: "update"
#    hibernate.ddl-auto: "create-drop"
    show-sql: true
  redis:
    host: ec2-3-88-85-162.compute-1.amazonaws.com
    port: 6379
#    database: 0
    timeout: 3000 #最大等待时间，3000ms,超时抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1