INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('MALH','Malahide','53.4508','-6.1546',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DUK','Dundalk','54.0037','-6.4028',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DRO','Drogheda','53.7187','-6.3478',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DNA','Donabate','53.4858','-6.1531',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('SWO','Swords','53.4597','-6.2183',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('BALL','Ballincollig','51.8833','-8.6167',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('BLA','Blanchardstown','53.3917','-6.3892',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('BRAY','Bray','53.2028','-6.0989',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('CBRA','Cabra','53.3617','-6.2917',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('CLON','Clontarf','53.3675','-6.2044',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('CLW','Carlow','52.8375','-6.9261',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('COB','Cobh','51.8536','-8.2997',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('COOL','Coolock','53.3889','-6.2233',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('COR','Cork','51.8969','-8.4863',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('CSTL','Castleknock','53.3753','-6.3636',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DAIR','Dublin Airport','53.4264','-6.2499',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DCN','Dublin area North','53.3478','-6.2725',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DCS','Dublin area South','53.3417','-6.2697',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DCSW','Dublin Central South West','53.3403','-6.2916',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DRU','Drumcondra','53.3708','-6.2519',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DUBP','Dublin Port','53.3499','-6.2238',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('DUN','Dundrum','53.2925','-6.2411',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('FING','Finglas','53.3906','-6.2989',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('FXR','Foxrock','53.2667','-6.1833',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('GAL','Galway','53.2707','-9.0568',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('KLK','Kilkenny','52.6541','-7.2448',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('KYLE','Kylemore','53.3314','-6.3206',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('LEIX','Leixlip','53.3631','-6.49',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('LIM','Limerick','52.668','-8.6305',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('MHW','Mahon West','51.8833','-8.4',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('MLH','Mulhuddart','53.4033','-6.4047',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('NAAS','Naas','53.2159','-6.6669',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('NAV','Navan','53.6529','-6.6814',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('NBR','Newbridge','53.1811','-6.7985',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('NDB','North Dublin','53.3865','-6.3166',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('NUNS','Nuns Island','53.2717','-9.0581',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('PTL','Portlaoise','53.0344','-7.2992',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('RONT','Ronanstown','53.3653','-6.425',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('SHN','Shankill','53.2286','-6.1162',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('TAL','Tallaght','53.2859','-6.3733',0);
INSERT INTO area(abbreviation,area_name, latitude, longitude, country) VALUES ('WRTF','Waterford','52.2593','-7.1101',0);

INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('LDN','London','51.5074','-0.1278',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('BIR','Birmingham','52.4862','-1.8904',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('MAN','Manchester','53.4839','-2.2446',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('GLA','Glasgow','55.8642','-4.2518',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('EDN','Edinburgh','55.9533','-2.9916',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('LIV','Liverpool','53.4084','-2.9916',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('LDS','Leeds','53.8013','-1.5486',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('BRS','Bristol','51.4545','-2.5879',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('SHF','Sheffield','53.3811','-1.4701',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('NCL','Newcastle upon Tyne','54.9783','-1.6174',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('NOT','Nottingham','52.9548','-1.1581',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('CDF','Cardiff','51.4816','-3.1791',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('BEL','Belfast','54.5973','-5.9301',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('SOU','Southampton','50.9097','-1.4044',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('PLY','Plymouth','50.3755','-4.1427',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('OXF','Oxford','51.752','-1.2577',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('CAM','Cambridge','52.2053','0.1218',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('ABD','Aberdeen','57.1497','-2.0943',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('DND','Dundee','56.462','-2.9707',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('YRK','York','53.9591','-1.0815',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('BTN','Brighton','50.8225','-0.1372',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('POM','Portsmouth','50.8167','-1.0833',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('SWA','Swansea','51.6214','-3.9436',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('COV','Coventry','52.4068','-1.5197',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('WOL','Wolverhampton','52.586','-2.1288',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('DER','Derby','52.9228','-1.4762',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('HUL','Hull','53.7512','-0.3359',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('NRW','Norwich','52.6309','1.2974',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('SUN','Sunderland','54.9061','-1.3811',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('LUT','Luton','51.8787','-0.42',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('SWI','Swindon','51.5558','-1.7797',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('WOK','Woking','51.319','-0.5589',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('RDG','Reading','51.4543','-0.9781',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('BNE','Bournemouth','50.7208','-1.9046',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('PRE','Preston','53.7632','-2.7031',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('BLB','Blackburn','53.7486','-2.4851',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('MAI','Maidstone','51.2704','0.5227',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('BKH','Brikenhead','53.3934','-3.0148',1);
INSERT INTO area(abbreviation, area_name, latitude, longitude, country) VALUES ('NPT','Newport','51.5877','-2.9984',1);